export { default as profile } from "./profile.png";
export { default as about } from "./about.png";
export { default as project } from "./project.png";
export { default as skills } from "./skills.png";
export { default as avatar } from "./avatar.jpg";
export { default as git } from "./git.png";
export { default as request } from "./request.png";
export { default as website } from "./website.png";
export { default as cat } from "./xd.gif";
